//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseGet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParseGet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Cancelled..
        /// </summary>
        internal static string DownloadCancelled {
            get {
                return ResourceManager.GetString("DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed..
        /// </summary>
        internal static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data ... .
        /// </summary>
        internal static string DownloadData {
            get {
                return ResourceManager.GetString("DownloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data (Partial Content)... .
        /// </summary>
        internal static string DownloadPartialData {
            get {
                return ResourceManager.GetString("DownloadPartialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invaild URL..
        /// </summary>
        internal static string ErrorInvalidURL {
            get {
                return ResourceManager.GetString("ErrorInvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: A same URL already in task list..
        /// </summary>
        internal static string ErrorSameURL {
            get {
                return ResourceManager.GetString("ErrorSameURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input FM5K Code:.
        /// </summary>
        internal static string InputFM5K {
            get {
                return ResourceManager.GetString("InputFM5K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input FTN5K Code:.
        /// </summary>
        internal static string InputFTN5K {
            get {
                return ResourceManager.GetString("InputFTN5K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging ....
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task Added.
        /// </summary>
        internal static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving real download url ....
        /// </summary>
        internal static string RetrieveURL {
            get {
                return ResourceManager.GetString("RetrieveURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify age ....
        /// </summary>
        internal static string VerifyAge {
            get {
                return ResourceManager.GetString("VerifyAge", resourceCulture);
            }
        }
    }
}
